<Project>
  <PropertyGroup>
    <VersionPrefix>0.0.1</VersionPrefix>
    <VersionSuffix>alpha</VersionSuffix>
    <Version>$(VersionPrefix)-$(VersionSuffix)</Version>
    <AssemblyVersion>0.0.1.0</AssemblyVersion>
    <FileVersion>0.0.1.0</FileVersion>
    <InformationalVersion>$(Version)</InformationalVersion>
    <Product>VeloCenter</Product>
    <Authors>oliwier93</Authors>
    <RepositoryUrl>https://github.com/oliwier93/velo-center</RepositoryUrl>
  </PropertyGroup>

  <PropertyGroup Condition="'$(UseArtifactsOutput)' == 'true'">
    <ArtifactsRoot Condition="'$(ArtifactsRoot)' == ''">$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory).artifacts\build\'))</ArtifactsRoot>
    <BaseIntermediateOutputPath>$(ArtifactsRoot)obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <BaseOutputPath>$(ArtifactsRoot)bin\$(MSBuildProjectName)\</BaseOutputPath>
  </PropertyGroup>
</Project>
