//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("VeloCenter.App")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+f8be1471f511d3e6961164e37b3680f72bc754c5")]
[assembly: System.Reflection.AssemblyProductAttribute("VeloCenter.App")]
[assembly: System.Reflection.AssemblyTitleAttribute("VeloCenter.App")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

// Wygenerowane przez klasę WriteCodeFragment programu MSBuild.

